// Code generated by aocgen; DO NOT EDIT.
package year2022

type Day17 struct{}

func (p Day17) PartA(lines []string) any {
	return "implement_me"
}

func (p Day17) PartB(lines []string) any {
	return "implement_me"
}
