// Code generated by aocgen; DO NOT EDIT.
package year2022

type Day13 struct{}

func (p Day13) PartA(lines []string) any {
	return "implement_me"
}

func (p Day13) PartB(lines []string) any {
	return "implement_me"
}
