// Code generated by aocgen; DO NOT EDIT.
package year2021

import (
	"strings"
	"testing"

	"aocgen/pkg/aoc"
)

const example = ""

func TestDay05PartA(t *testing.T) {
	Init()
	input := strings.Split(example, "\n")
	p := aoc.NewPuzzle(2021, 5)

	p.PartA(input)
	// assert here
}

func TestDay05PartB(t *testing.T) {
	Init()
	input := strings.Split(example, "\n")
	p := aoc.NewPuzzle(2021, 5)

	p.PartB(input)
	// assert here
}
